backend:
    name: git-gateway
    branch: main

local_backend: true
logo_url: https://alpenglowcounselingvt.com/assets/images/logo.png

media_folder: "src/assets/images/blog"
public_folder: "/assets/images/blog"

collections:
    # Blog Collection
    - name: "blog"
      label: "Blog"
      folder: "src/content/blog"
      create: true
      slug: "{{slug}}"
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
                label: "URL Slug",
                name: "url",
                widget: "string",
                hint: 'Specify where the page will be written to. If you use "Blog Post", the post will be accessible from "blog/blog-post"',
            }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Author", name: "author", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
          - { label: "Featured Image", name: "image", widget: "image" }
          - { label: "Image Caption", name: "imageAlt", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
    
    # Settings Collection for Banner
    - name: "settings"
      label: "Site Settings"
      files:
          - name: "banner"
            label: "Client Acceptance Banner"
            file: "src/_data/banner.json"
            fields:
                - {label: "Show Banner", name: "show_banner", widget: "boolean", default: false}
                - {label: "Banner Message", name: "message", widget: "text", default: "We are not currently accepting new clients. Please check back later or join our waitlist for future openings."}
                - {label: "Waitlist Link (optional)", name: "waitlist_link", widget: "string", required: false}
